api = "0.7"

[buildpack]
  description = "A buildpack for compiling Go applications and writing start commands"
  homepage = "https://github.com/paketo-buildpacks/go-build"
  id = "paketo-buildpacks/go-build"
  keywords = ["go", "build", "compilation", "binary"]
  name = "Paketo Buildpack for Go Build"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]
  version = "2.2.25"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go-build/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"
